// This file was auto-generated by Fern from our API Definition.

package client

import (
	configurations "github.com/fluidstackio/fluidstack-go-sdk/configurations"
	core "github.com/fluidstackio/fluidstack-go-sdk/core"
	instances "github.com/fluidstackio/fluidstack-go-sdk/instances"
	internal "github.com/fluidstackio/fluidstack-go-sdk/internal"
	option "github.com/fluidstackio/fluidstack-go-sdk/option"
	sshkeys "github.com/fluidstackio/fluidstack-go-sdk/sshkeys"
	templates "github.com/fluidstackio/fluidstack-go-sdk/templates"
	http "net/http"
	os "os"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Instances      *instances.Client
	SshKeys        *sshkeys.Client
	Configurations *configurations.Client
	Templates      *templates.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.ApiKey == "" {
		options.ApiKey = os.Getenv("FLUIDSTACK_API_KEY")
	}
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:         options.ToHeader(),
		Instances:      instances.NewClient(opts...),
		SshKeys:        sshkeys.NewClient(opts...),
		Configurations: configurations.NewClient(opts...),
		Templates:      templates.NewClient(opts...),
	}
}
