// This file was auto-generated by Fern from our API Definition.

package fluidstack

import (
	json "encoding/json"
	core "github.com/fluidstackio/fluidstack-go-sdk/core"
)

// Authentication Error
type UnauthorizedError struct {
	*core.APIError
	Body *Message
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *Message
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

// Validation Error
type UnprocessableEntityError struct {
	*core.APIError
	Body *HttpValidationError
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *HttpValidationError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}
