// This file was auto-generated by Fern from our API Definition.

package fluidstack

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fluidstackio/fluidstack-go-sdk/internal"
)

type TemplatesListRequest struct {
	ApiKey *string `json:"-" url:"-"`
}

type OperatingSystemResponse struct {
	// The friendly name of the operating system.
	Name string `json:"name" url:"name"`
	// The description of the operating system, detailing the pre-installed packages and customisations, if any.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The unique slug identifier of the operating system.
	Label SupportedOperatingSystem `json:"label" url:"label"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OperatingSystemResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OperatingSystemResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OperatingSystemResponse) GetLabel() SupportedOperatingSystem {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *OperatingSystemResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OperatingSystemResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OperatingSystemResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OperatingSystemResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OperatingSystemResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
